[package]
name = "adventofcode-2022"
version = "1.0.0"
description = "lavong's solutions to advent of code 2022"
authors = ["Lavong Soysavanh <lavong.soysavanh@gmail.com>"]
license-file = "LICENSE.txt"
edition = "2021"

[dependencies]
